name: Run the Crossposter
run-name: Running the Crossposter
on:
    schedule:
        - cron: '0 */2 * * *'
jobs:
    run-crossposter:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.12'
                  cache: pip
            - name: Install dependencies
              env:
                BSKY_PASSWORD: ${{secrets.BSKY_PASSWORD}}
                MASTODON_TOKEN: ${{secrets.MASTODON_TOKEN}}
              run: |
                  pip install -r requirements.txt
            - name: Run crossposter
              run: |
                  python run.py
            - name: Commit
              uses: GuillaumeFalourd/git-commit-push@v1.3
              with:
                  commit_message: github_action_commit